In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

In [2]:
df = pd.read_csv("../data/raw/resume_data.csv")

print(df.shape)

df.head()

(9544, 35)

,address,career_objective,skills,educational_institution_name,degree_names,passing_years,educational_results,result_types,major_field_of_studies,professional_company_names,...,online_links,issue_dates,expiry_dates,﻿job_position_name,educationaL_requirements,experiencere_requirement,age_requirement,responsibilities.1,skills_required,matched_score
0,NaN,Big data analytics working and database wareho...,"['Big Data', 'Hadoop', 'Hive', 'Python', 'Mapr...",['The Amity School of Engineering & Technology...,['B.Tech'],['2019'],['N/A'],[None],['Electronics'],['Coca-COla'],...,NaN,NaN,NaN,Senior Software Engineer,B.Sc in Computer Science & Engineering from a ...,At least 1 year,NaN,Technical Support\nTroubleshooting\nCollaborat...,NaN,0.850000
1,NaN,Fresher looking to join as a data analyst and ...,"['Data Analysis', 'Data Analytics', 'Business ...","['Delhi University - Hansraj College', 'Delhi ...","['B.Sc (Maths)', 'M.Sc (Science) (Statistics)']","['2015', '2018']","['N/A', 'N/A']","['N/A', 'N/A']","['Mathematics', 'Statistics']",['BIB Consultancy'],...,NaN,NaN,NaN,Machine Learning (ML) Engineer,M.Sc in Computer Science & Engineering or in a...,At least 5 year(s),NaN,Machine Learning Leadership\nCross-Functional ...,NaN,0.750000
2,NaN,NaN,"['Software Development', 'Machine Learning', '...","['Birla Institute of Technology (BIT), Ranchi']",['B.Tech'],['2018'],['N/A'],['N/A'],['Electronics/Telecommunication'],['Axis Bank Limited'],...,NaN,NaN,NaN,"Executive/ Senior Executive- Trade Marketing, ...",Master of Business Administration (MBA),At least 3 years,NaN,"Trade Marketing Executive\nBrand Visibility, S...",Brand Promotion\nCampaign Management\nField Su...,0.416667
3,NaN,To obtain a position in a fast-paced business ...,"['accounts payables', 'accounts receivables', ...","['Martinez Adult Education, Business Training ...",['Computer Applications Specialist Certificate...,['2008'],[None],[None],['Computer Applications'],"['Company Name ï¼ City , State', 'Company Name...",...,NaN,NaN,NaN,Business Development Executive,Bachelor/Honors,1 to 3 years,Age 22 to 30 years,Apparel Sourcing\nQuality Garment Sourcing\nRe...,Fast typing skill\nIELTSInternet browsing & on...,0.760000
4,NaN,Professional accountant with an outstanding wo...,"['Analytical reasoning', 'Compliance testing k...",['Kent State University'],['Bachelor of Business Administration'],[None],['3.84'],[None],['Accounting'],"['Company Name', 'Company Name', 'Company Name...",...,[None],[None],"['February 15, 2021']",Senior iOS Engineer,Bachelor of Science (BSc) in Computer Science,At least 4 years,NaN,iOS Lifecycle\nRequirement Analysis\nNative Fr...,iOS\niOS App Developer\niOS Application Develo...,0.650000

In [3]:
text_columns = [
    "career_objective",
    "skills",
    "major_field_of_studies",
    "related_skils_in_job",
    "positions",
    "responsibilities"
]

df["resume_text"] = (
    df[text_columns]
    .fillna("")
    .astype(str)
    .agg(" ".join, axis=1)
)

df["resume_text"].head()

0    Big data analytics working and database wareho...
1    Fresher looking to join as a data analyst and ...
2     ['Software Development', 'Machine Learning', ...
3    To obtain a position in a fast-paced business ...
4    Professional accountant with an outstanding wo...
Name: resume_text, dtype: str

In [4]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-Z\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df["clean_resume"] = df["resume_text"].apply(clean_text)

df["clean_resume"].head()

0    big data analytics working and database wareho...
1    fresher looking to join as a data analyst and ...
2    software development machine learning deep lea...
3    to obtain a position in a fast paced business ...
4    professional accountant with an outstanding wo...
Name: clean_resume, dtype: str

In [5]:
tfidf = TfidfVectorizer(
    stop_words="english",
    max_features=5000
)

X = tfidf.fit_transform(df["clean_resume"])

print(X.shape)

(9544, 3578)

In [6]:
from sklearn.cluster import KMeans

kmeans = KMeans(
    n_clusters=10,
    random_state=42,
    n_init=10
)

kmeans.fit(X)

print("✅ Clustering Completed")

✅ Clustering Completed

In [7]:
df["cluster"] = kmeans.labels_

df[["positions", "cluster"]].head()

                                           positions  cluster
0                               ['Big Data Analyst']        5
1                               ['Business Analyst']        2
2  ['Software Developer (Machine Learning Enginee...        7
3  ['Accountant', 'Accounts Receivable Clerk', 'M...        8
4  ['Staff Accountant', 'Senior Accountant', 'Tax...        8

In [8]:
print(df["cluster"].value_counts())

cluster
1    2864
5    1846
0    1612
8    1150
4     599
3     400
6     286
2     280
9     274
7     233
Name: count, dtype: int64

In [9]:
for cluster in sorted(df["cluster"].unique()):
    print("=" * 50)
    print(f"Cluster {cluster}")

    print(
        df[df["cluster"] == cluster]["positions"]
        .value_counts()
        .head(10)
    )

==================================================
Cluster 0
positions
['Intern']                              195
['Intern Trainee']                       67
['SDE']                                  46
['Junior Machine Learning Engineer']     45
['Analyst Intern']                       45
['Software Developer']                   44
['Machine Learning Engineer']            44
['Data Scientist']                       43
['SDE Intern']                           42
['Machine Learning Developer']           24
Name: count, dtype: int64
==================================================
Cluster 1
positions
['Corporate Process/Systems Engineering Manager', 'SDI Site Operations Manager', 'Operations Group Manager']                                                                                                                                                            28
['QA Engineering Manager', 'Software Certification Analyst', 'Project Lead']                                                                                                                                                                                            28
['Corporate Engineering Support Technician', 'Help Desk Support Analyst II']                                                                                                                                                                                            28
['Engineering Planning Manager', 'Senior Manufacturing Project Engineer', 'Production Planner', 'Production Manager', 'Department Supervisor/Planner', 'Production Supervisor', 'Manufacturing Engineer']                                                               28
['QA Engineering Team Lead', 'Quality Assurance Engineering Manager', 'QA Lead for Customer Care/Service Applications', 'Mail - Software Quality Engineer II', 'Senior Quality Assurance Analyst', 'Software Quality Assurance']                                        28
['Engineering Lab Technician', 'Engineering Validation Test Technician', 'Electromechanical Technician']                                                                                                                                                                28
['Engineering Systems Installer', 'IT Technician/QA Tester', 'Installation/Service Technician']                                                                                                                                                                         27
['Equipment Engineering Technician', 'Mechanical Technician', 'Operating Engineer / Test Technician', 'Logistics Coordinator / Sr. Lab Technician', 'Production Control Analyst', 'Material/Production Planner']                                                        27
['Clinical Engineering Manager', 'Imaging Service Engineer', 'Imaging Service Engineer', 'Biomedical Equipment Technician II']                                                                                                                                          27
['Engineering Manager', 'Manager - Maintenance and Reliability', 'Supervisor Reliability Engineer', 'Process & Tooling Engineer', 'Converting Plant Engineer', 'Senior Converting Analyst', 'Development Designer, Mechanical Engineer, Senior Mechanical Engineer']    27
Name: count, dtype: int64
==================================================
Cluster 2
positions
['Intern']                                                                                                              14
['Intern Trainee']                                                                                                       5
['Software Engineering Manager', 'Software Engineering Manager', 'Principal Software Engineer', 'Software Engineer']     4
['Data Analyst']                                                                                                         4
['Business Analyst']                                                                                                     3
['SDE']                                                                                                                  3
['Machine Learning Engineer']                                                                                            3
['Data Scientist']                                                                                                       3
['Software Developer']                                                                                                   2
['N/A']                                                                                                                  2
Name: count, dtype: int64
==================================================
Cluster 3
positions
['Software Engineering Manager', 'Software Engineering Manager', 'Principal Software Engineer', 'Software Engineer']    103
['Intern']                                                                                                               14
['Intern Trainee']                                                                                                        5
['Data Analyst']                                                                                                          4
['Data Scientist']                                                                                                        3
['Machine Learning Engineer']                                                                                             3
['Business Analyst']                                                                                                      3
['SDE']                                                                                                                   3
['Accountant']                                                                                                            2
['Machine Learning Developer']                                                                                            2
Name: count, dtype: int64
==================================================
Cluster 4
positions
['Director of Engineering', 'Sr. Director Software Development', 'VP of Engineering and Operations', 'CTO', 'Co-Founder and COO', 'VP of Engineering', 'VP Solutions Sales', 'CTO', 'Independent Consultant', 'CTO & Founder']    28
['Business Development Manager', 'Sales and Marketing Manager', 'VP Sales and Marketing', 'Executive Assistant']                                                                                                                  28
['New Business Development Manager', 'Inside Sales Manager', 'Inside Sales Manager']                                                                                                                                              28
['Director of Business Development', 'Inside Sales Representative', 'General Manager', 'Assistant Manager']                                                                                                                       28
['Director of Business Development', 'Director of Franchise Sales', 'N/A']                                                                                                                                                        28
['Senior Business Development Manager', 'Business Development / Sales Manager', 'Marketing Manager', 'Senior Mortgage Specialist']                                                                                                28
['Business Development Analyst', 'Business Enterprise Risk Manager', 'Business Client Relationship Manager', 'Project Manager']                                                                                                   28
['Business Development Manager', 'Account Executive', 'Senior Account Executive', 'Manager', 'Sales Account Manager', 'Key Account Manager']                                                                                      28
['Business Development Manager', 'Event Manager', 'Customer Service Call Center Manager', 'Customer Service Representative / Call Center']                                                                                        27
['Business Development Manager', 'Area Sales Executive', 'Business Development Manager', 'Store Manager', 'Floor Manager']                                                                                                        27
Name: count, dtype: int64
==================================================
Cluster 5
positions
['Intern']                                                                                                                                         124
['Data Analyst']                                                                                                                                    91
['Business Analyst']                                                                                                                                68
['Intern Trainee']                                                                                                                                  48
['Junior Analyst Expert']                                                                                                                           45
['Engineering and Quality Technician', 'Lecturer in Environmental Science and Technology', 'Assistant Lecturer in Natural Resource Management']     28
['N/A']                                                                                                                                             26
['Data Scientist']                                                                                                                                  26
['Analyst']                                                                                                                                         26
['Machine Learning Engineer']                                                                                                                       25
Name: count, dtype: int64
==================================================
Cluster 6
positions
['Intern']                                                                                                              14
['Intern Trainee']                                                                                                       5
['Data Analyst']                                                                                                         4
['Software Engineering Manager', 'Software Engineering Manager', 'Principal Software Engineer', 'Software Engineer']     4
['Business Analyst']                                                                                                     3
['Data Scientist']                                                                                                       3
['Machine Learning Engineer']                                                                                            3
['SDE']                                                                                                                  3
['Junior Analyst Expert']                                                                                                2
['Software Developer']                                                                                                   2
Name: count, dtype: int64
==================================================
Cluster 7
positions
['Intern']                              14
['Intern Trainee']                       5
['Data Analyst']                         4
['Data Scientist']                       3
['SDE']                                  3
['Machine Learning Engineer']            3
['Business Analyst']                     3
['Analyst Intern']                       2
['Junior Machine Learning Engineer']     2
['Analyst']                              2
Name: count, dtype: int64
==================================================
Cluster 8
positions
['Accountant']                                                                                                                                                                     48
['Staff Accountant', 'Senior Accountant', 'Tax Analyst', 'Staff Accountant II', 'Staff Auditor II']                                                                                28
['Project Accountant', 'Project Administrator Engineering', 'Project Administrator', 'Senior Staff Accountant']                                                                    28
['Staff Accountant', 'Independent Accounting Consultant', 'Accounting Manager/Human Resources', 'Accounting and Human Resources Manager']                                          28
['Staff Accountant', 'Staff Accountant', 'Staff Accountant', 'Financial Management Partner']                                                                                       28
['Accountant', 'Office Manager/Restaurant Manager', 'Office Manager', 'Assistant Controller', 'Bookkeeper/Office Manager', 'Office Manager/Bookkeeper', 'Secretary/Bookkeeper']    28
['Supervisor Accountant', 'Lead Accountant', 'Senior Accountant', 'Senior Financial Analyst', 'General Accountant', 'Accountant']                                                  28
['Senior Accountant', 'Accountants Payable/Receivable & Purchasing Administrator', 'Accountant', 'Accounts Receivable & Collection Manager', 'Accountant']                         28
['Accountant', 'Staff Accountant', 'Accountant /Auditor']                                                                                                                          28
['Accountant', 'Accountant', 'Staff Accountant/ Lease Administrator', 'Assistant Claim Approver', 'Proof Operator', 'Billing Associate', 'Account Receivable Clerk']               28
Name: count, dtype: int64
==================================================
Cluster 9
positions
['Android Developer Intern', 'Android Developer Intern']    24
['Intern']                                                  14
['Intern Trainee']                                           5
['Data Analyst']                                             4
['Data Scientist']                                           3
['Machine Learning Engineer']                                3
['SDE']                                                      3
['Business Analyst']                                         3
['Analyst']                                                  2
['Analyst Intern']                                           2
Name: count, dtype: int64